const data = [
    {
        name: "Cox's-Bazar Tour",
        img1: "https://i.ibb.co/cgSsNZX/cox-bazar1.jpg",
        img2: "https://i.ibb.co/wssBnQt/cox-bazar2.jpg",
        img3: "https://i.ibb.co/bQjdfQP/cox-bazar3.jpg",
        cost: "6000",
        checkInDate: "11-2-2022",
        checkOutDate: "14-2-2022",
        overview: "Day 01: Leave Dhaka for Cox's Bazar by reserved car/coach - Overnight journey. Day 02: Cox's Bazar at 08 am. Breakfast and short beach tour. After lunch, start journey to Inani Beach, Himchhari Falls. Back to coxs bazar sea beach. Enjoy Sunset and night beach, Overnight at Cox's Bazar. Day 03: Enjoy the morning beach.After lunch, start for Moheshkhali Island by boat.Back to cox's bazar and visit barmiz market. Overnight at Cox's Bazar.Reach Dhaka at Morning. - End of Tour - ",
        included: {
            breakfast: true,
            lunch: true,
            dinner: true,
            gratuities: false,
            stayCost: true
        },
        planFor: "3-days",
    },
    {
        name: "Bandarban Tour",
        img1: "https://i.ibb.co/1Tj0Rr2/bandarban1.jpg",
        img2: "https://i.ibb.co/yQKgPNV/bandarban2.jpg",
        img3: "https://i.ibb.co/QD3BXSc/bandarban3.jpg",
        cost: "8700",
        checkInDate: "14-1-2022",
        checkOutDate: "18-1-2022",
        overview: "Bandarban is located in the south-eastern part of Bangladesh on the Chittagong division. Important to realize, among the three Chittagong Hill Tracks districts, Bandarban is one of them. In addition, it is the most beautiful and picturesque place in Bangladesh. It is one of the attractive travel destinations is just 77 km away from the Chittagong city. In Bandarban, the most beautiful tourist spots are Boga Lake, Chimbuk Hill and Tribal Villages,  Buddha Dhatu Jadi, Keokradong, Nilachal Tourist Spot, Mirinja Parjatan, Meghla Tourist Spot, Nafakhum and Remakri, Nilgiri and Thanchi, Rijuk Waterfall, Prantik Lake, Sangu River, Tajingdong, Shoilo Propat, and Upabon Parjatan.",
        included: {
            breakfast: true,
            lunch: false,
            dinner: true,
            gratuities: true,
            stayCost: true
        },
        planFor: "4-days",
    },
    {
        name: "Sylhet Tour",
        img1: "https://i.ibb.co/2Mz6hSJ/sylhet1.jpg",
        img2: "https://i.ibb.co/NNQHQCQ/sylhet2.jpg",
        img3: "https://i.ibb.co/q72k3hq/sylhet3.jpg",
        cost: "5000",
        checkInDate: "13-12-2021",
        checkOutDate: "16-12-2021",
        overview: "Sylhet, lying on the banks Surma River, is considered to be one of the most beautiful cities in Bangladesh. With lush, refreshing greenery, it is known as the Land of Fairies! Keane Bridge is the gateway to Sylhet and also a prominent landmark. Ratargul is another lovely spot to visit when you are in Sylhet. This swamp forest is one-of-its-kind and the views here are absolutely stunning! One of the few freshwater swamp forests in Bangladesh, it's a must visit. Visit the forest during winter to enjoy the beauty at its peak. Tambil-Jaflong is where you'll witness inspiring views of the surrounding greenery and also get a chance to visit the waterfalls. Do also visit Sree Mangal, considered to be the largest tea gardens in the world. Pangthumai Waterfall and Satchari National Park are some of the other places you can visit when you are around Sylhet. If Sylhet is the only place on your itinerary, be aware that only a few hours are sufficient to explore and learn about the place.",
        included: {
            breakfast: true,
            lunch: true,
            dinner: true,
            gratuities: true,
            stayCost: true
        },
        planFor: "3-days",
    },
    {
        name: "Sajek Valley Tour",
        img1: "https://i.ibb.co/VMxsX9B/shajek1.jpg",
        img2: "https://i.ibb.co/LSc6GQM/shajek2.jpg",
        img3: "https://i.ibb.co/jRpXGFt/shajek3.jpg",
        cost: "9000",
        checkInDate: "18-12-2021",
        checkOutDate: "23-12-2021",
        overview: "Who does not want to be lost in a white cloud-like cotton? Sajek Valley, currently the most popular destination for pilgrims/travelers, is located in the biggest union of Bangladesh, Baghaichari Upazila of Rangamati district. It is on the border of Mizoram in the north of Rangamati district. The north side of Sajek is Tripura, Langadu of Rangamati on the south, Mizoram of India on the east, Khagrachori Dighinala on the west. The height of Sajek Valley from sea level is 1800 feet. Though the location of Sajek is in Rangamati district, it is very easy to travel from Dighinala to Khagrachari due to geographical reasons. Sajek is 70km away from Khagrachari district and 40 kilometers from Dighinala. If you want to go to Sajek, you will have to get permission from the Baghaihat Police or Army camp.",
        included: {
            breakfast: true,
            lunch: true,
            dinner: true,
            gratuities: false,
            stayCost: true
        },
        planFor: "5-days",
    },
    {
        name: "Sundarban Tour",
        img1: "https://i.ibb.co/rZZCYFV/sundarban1.jpg",
        img2: "https://i.ibb.co/zRnjvZg/sundarban2.jpg",
        img3: "https://i.ibb.co/kJSyznd/sundarban3.jpg",
        cost: "7000",
        checkInDate: "9-11-2021",
        checkOutDate: "11-11-2021",
        overview: "The Sundarbans are located at the point where the mighty waterways of the Brahmaputra and the scared Ganges crash into each other at the edge of the Bay of Bengal. As you would expect, the area is also covered in spectacular wildlife and is a UNESCO World Heritage Site.Here you will find Bengal tigers stalking the mangroves as well as rhesus macaques swinging in the canopies.Other highlights include chitals and you will also find local huts dotted around the area and hiding beneath waxy palm trees.",
        included: {
            breakfast: false,
            lunch: true,
            dinner: true,
            gratuities: false,
            stayCost: true
        },
        planFor: "2-days",
    },
    {
        name: "Saint Martin Tour",
        img1: "https://i.ibb.co/58Lvnr4/martin1.jpg",
        img2: "https://i.ibb.co/0MzrK5H/martin2.jpg",
        img3: "https://i.ibb.co/Vq5Sxvm/martin3.jpg",
        cost: "12000",
        checkInDate: "30-11-2021",
        checkOutDate: "3-12-2021",
        overview: "Saint Martin is one of the few coral islands in the world. Saint martin island in Bangladesh is called the blue heaven. Find the best hotels in st. martin & complete tour packages. Surrounding blue water, the island is way more gorgeous than you can imagine.Saint Martin tour is a small coral island in the heart of the Bay of Bengal.The island is made out of coral.This is the place where nature will definitely show you the definition of beauty.Enjoy an amazing ship journey on the blue Bay of Bengal.We designed the tour to make you feel every part of the beauty.",
        included: {
            breakfast: false,
            lunch: false,
            dinner: true,
            gratuities: false,
            stayCost: true
        },
        planFor: "3-days",
    },
]